"""empty message

Revision ID: 3404c7b785e0
Revises: b29b2550ea52
Create Date: 2017-09-15 17:59:01.411015

"""

# revision identifiers, used by Alembic.
revision = '3404c7b785e0'
down_revision = 'b29b2550ea52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phone_ddd', table_name='phone')
    op.create_index(op.f('ix_phone_ddd'), 'phone', ['ddd'], unique=False)
    op.drop_index('ix_phone_number', table_name='phone')
    op.create_index(op.f('ix_phone_number'), 'phone', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_number'), table_name='phone')
    op.create_index('ix_phone_number', 'phone', ['number'], unique=True)
    op.drop_index(op.f('ix_phone_ddd'), table_name='phone')
    op.create_index('ix_phone_ddd', 'phone', ['ddd'], unique=True)
    # ### end Alembic commands ###
