"""empty message

Revision ID: b29b2550ea52
Revises: e0b73fbbb1cb
Create Date: 2017-08-30 21:47:10.273761

"""

# revision identifiers, used by Alembic.
revision = 'b29b2550ea52'
down_revision = 'e0b73fbbb1cb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_phone_user_id'), 'phone', ['user_id'], unique=False)
    op.drop_index('ix_phone_ddd', table_name='phone')
    op.create_index(op.f('ix_phone_ddd'), 'phone', ['ddd'], unique=True)
    op.drop_index('ix_phone_number', table_name='phone')
    op.create_index(op.f('ix_phone_number'), 'phone', ['number'], unique=True)
    op.add_column('user', sa.Column('last_name', sa.String(length=200), nullable=False))
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_updated_on'), 'user', ['updated_on'], unique=False)
    op.drop_column('user', 'last_login_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_index(op.f('ix_user_updated_on'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_column('user', 'last_name')
    op.drop_index(op.f('ix_phone_number'), table_name='phone')
    op.create_index('ix_phone_number', 'phone', ['number'], unique=False)
    op.drop_index(op.f('ix_phone_ddd'), table_name='phone')
    op.create_index('ix_phone_ddd', 'phone', ['ddd'], unique=False)
    op.drop_index(op.f('ix_phone_user_id'), table_name='phone')
    # ### end Alembic commands ###
